/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uangkuapplication.view;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import uangkuapplication.controller.KategoriController;
import uangkuapplication.database.UangkuDatabase;
import uangkuapplication.entity.EntityKategori;
import uangkuapplication.error.KategoriException;
import uangkuapplication.event.KategoriListener;
import uangkuapplication.main.UangkuApplication;
import uangkuapplication.model.ModelKategori;
import uangkuapplication.model.ModelTableKategori;
import uangkuapplication.service.IKategori;

/**
 *
 * @author Kyoto
 */
public class KategoriFrame extends javax.swing.JFrame implements KategoriListener, ListSelectionListener{

    private ModelTableKategori kategoriModel;
    private ModelKategori model;
    private KategoriController controller;
    
    public KategoriFrame() {
        kategoriModel = new ModelTableKategori();
        model = new ModelKategori();
        model.setListener(this);
        controller = new KategoriController();
        controller.setModel(model);
        initComponents();
        tableKategori.getSelectionModel().addListSelectionListener(this);
        tableKategori.setModel(kategoriModel);
    }

    public JTable getTableKategori() {
        return tableKategori;
    }

    public JTextField getTxtIdKategori() {
        return txtIdKategori;
    }

    public JTextField getTxtNamaKategori() {
        return txtNamaKategori;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIdKategori = new javax.swing.JTextField();
        btnSimpanKategori = new javax.swing.JButton();
        btnResetKategori = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableKategori = new javax.swing.JTable();
        btnUbahKategori = new javax.swing.JButton();
        btnHapusKategori = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtNamaKategori = new javax.swing.JTextField();

        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        jLabel1.setText("Tambah kategori");

        jLabel2.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        jLabel2.setText("Id");

        txtIdKategori.setEditable(false);
        txtIdKategori.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnSimpanKategori.setBackground(new java.awt.Color(255, 229, 153));
        btnSimpanKategori.setFont(new java.awt.Font("Lato", 0, 11)); // NOI18N
        btnSimpanKategori.setForeground(new java.awt.Color(38, 50, 56));
        btnSimpanKategori.setText("Simpan");
        btnSimpanKategori.setBorder(null);
        btnSimpanKategori.setBorderPainted(false);
        btnSimpanKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanKategoriActionPerformed(evt);
            }
        });

        btnResetKategori.setBackground(new java.awt.Color(235, 87, 87));
        btnResetKategori.setFont(new java.awt.Font("Lato", 0, 11)); // NOI18N
        btnResetKategori.setForeground(new java.awt.Color(255, 255, 255));
        btnResetKategori.setText("Reset");
        btnResetKategori.setBorder(null);
        btnResetKategori.setBorderPainted(false);
        btnResetKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetKategoriActionPerformed(evt);
            }
        });

        tableKategori.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableKategori);

        btnUbahKategori.setBackground(new java.awt.Color(255, 229, 153));
        btnUbahKategori.setFont(new java.awt.Font("Lato", 0, 11)); // NOI18N
        btnUbahKategori.setForeground(new java.awt.Color(38, 50, 56));
        btnUbahKategori.setText("Ubah");
        btnUbahKategori.setBorder(null);
        btnUbahKategori.setBorderPainted(false);
        btnUbahKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahKategoriActionPerformed(evt);
            }
        });

        btnHapusKategori.setBackground(new java.awt.Color(235, 87, 87));
        btnHapusKategori.setFont(new java.awt.Font("Lato", 0, 11)); // NOI18N
        btnHapusKategori.setForeground(new java.awt.Color(255, 255, 255));
        btnHapusKategori.setText("Hapus");
        btnHapusKategori.setBorder(null);
        btnHapusKategori.setBorderPainted(false);
        btnHapusKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusKategoriActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        jLabel3.setText("Nama kategori");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnSimpanKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnHapusKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnResetKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnUbahKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIdKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(txtNamaKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamaKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpanKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUbahKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnResetKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapusKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetKategoriActionPerformed
        controller.resetKategori(this);
    }//GEN-LAST:event_btnResetKategoriActionPerformed

    private void btnHapusKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusKategoriActionPerformed
        controller.deleteKategori(this);
    }//GEN-LAST:event_btnHapusKategoriActionPerformed

    private void btnUbahKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahKategoriActionPerformed
        controller.updateKategori(this);
    }//GEN-LAST:event_btnUbahKategoriActionPerformed

    private void btnSimpanKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanKategoriActionPerformed
        controller.insertKategori(this);
    }//GEN-LAST:event_btnSimpanKategoriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KategoriFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KategoriFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KategoriFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KategoriFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KategoriFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapusKategori;
    private javax.swing.JButton btnResetKategori;
    private javax.swing.JButton btnSimpanKategori;
    private javax.swing.JButton btnUbahKategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableKategori;
    private javax.swing.JTextField txtIdKategori;
    private javax.swing.JTextField txtNamaKategori;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onChange(ModelKategori model) {
        txtIdKategori.setText(model.getId() + "");
        txtNamaKategori.setText(model.getNama_kategori());
        
    }

    @Override
    public void onInsert(EntityKategori kategori) {
        kategoriModel.add(kategori);
        try {
            UangkuApplication.kategoriList = UangkuDatabase.getKategori().getAllKategori();
        } catch (SQLException ex) {
            Logger.getLogger(KategoriFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    @Override
    public void onDelete() {
        int index = tableKategori.getSelectedRow();
        kategoriModel.remove(index);
        try {
            UangkuApplication.kategoriList = UangkuDatabase.getKategori().getAllKategori();
        } catch (SQLException ex) {
            Logger.getLogger(KategoriFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Override
    public void onUpdate(EntityKategori kategori) {
        int index = tableKategori.getSelectedRow();
        kategoriModel.set(index, kategori);
        try {
            UangkuApplication.kategoriList = UangkuDatabase.getKategori().getAllKategori();
        } catch (SQLException ex) {
            Logger.getLogger(KategoriFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Override
    public void valueChanged(ListSelectionEvent lse) {
        try {
            EntityKategori model = kategoriModel.get(tableKategori.getSelectedRow());
            txtIdKategori.setText(model.getId() + "");
            txtNamaKategori.setText(model.getNama_kategori());
            try {
                UangkuApplication.kategoriList = UangkuDatabase.getKategori().getAllKategori();
            } catch (SQLException ex) {
                Logger.getLogger(KategoriFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (IndexOutOfBoundsException e) {
        }
    }
    
    public void loadDatabase() throws SQLException, KategoriException{
        IKategori dao = UangkuDatabase.getKategori();
        kategoriModel.setList(dao.getAllKategori());
    }
}
